# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: library.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'library.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlibrary.proto\x12\x07library\",\n\x0b\x42ookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"3\n\x0eReserveRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\"0\n\x0c\x42ookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"Y\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x11\n\tavailable\x18\x04 \x01(\x08\x12\x13\n\x0breserved_by\x18\x05 \x01(\t\"(\n\x08\x42ookList\x12\x1c\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\r.library.Book\"2\n\rReturnRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t2\xf0\x01\n\x0b\x42ookService\x12\x36\n\x07\x41\x64\x64\x42ook\x12\x14.library.BookRequest\x1a\x15.library.BookResponse\x12=\n\x0bReserveBook\x12\x17.library.ReserveRequest\x1a\x15.library.BookResponse\x12-\n\x08GetBooks\x12\x0e.library.Empty\x1a\x11.library.BookList\x12;\n\nReturnBook\x12\x16.library.ReturnRequest\x1a\x15.library.BookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'library_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=26
  _globals['_BOOKREQUEST']._serialized_end=70
  _globals['_RESERVEREQUEST']._serialized_start=72
  _globals['_RESERVEREQUEST']._serialized_end=123
  _globals['_BOOKRESPONSE']._serialized_start=125
  _globals['_BOOKRESPONSE']._serialized_end=173
  _globals['_EMPTY']._serialized_start=175
  _globals['_EMPTY']._serialized_end=182
  _globals['_BOOK']._serialized_start=184
  _globals['_BOOK']._serialized_end=273
  _globals['_BOOKLIST']._serialized_start=275
  _globals['_BOOKLIST']._serialized_end=315
  _globals['_RETURNREQUEST']._serialized_start=317
  _globals['_RETURNREQUEST']._serialized_end=367
  _globals['_BOOKSERVICE']._serialized_start=370
  _globals['_BOOKSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
